server:
  port: 26000
spring:
  profiles:
    active: eureka
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        # 静态路由配置
#        - id: order-service
#          uri: http://localhost:10007
#          predicates:
#            - Path=/order/**
        # 动态路由配置
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
