server:
  port: 10006
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 10
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:33010/my_test?rewriteBatchedStatements=true&max_allowed_packet=10M&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: eureka
ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
  MaxAutoRetriesNextServer: 0
  MaxAutoRetries: 0
  ReadTimeout: 10000
feign:
  # 压缩
  compression:
    request:
      enabled: true
    response:
      enabled: true
  client:
    config:
      order-service:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: full
  hystrix:
    enabled: true
mybatis-plus:
  type-aliases-package: com.webbdong.userservice.model.entity
  configuration:
    # 设置驼峰命名规则
    map-underscore-to-camel-case: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
hystrix:
  dashboard:
    proxy-stream-allow-list: "localhost"